// Commands module
pub mod afk;
pub mod config;
pub mod export;
pub mod help;
pub mod immersion;
pub mod leaderboard;
pub mod log;
pub mod novel;
pub mod prompt;
pub mod react;
pub mod register;
pub mod role_rank;
pub mod stat;
pub mod subs;
